product:
  info:
    service:
      base:
        url: http://product-info:8080
  price:
    service:
      base:
        url: http://product-price:8080
feign:
  client:
    config:
      default:
        errorDecoder: com.target.composite.product.util.exception.decoder.CustomErrorDecoder
