spring:
  redis:
    host: localhost
    port: 6378
    cache:
      type: redis
server:
  port: 8380
product:
  info:
    service:
      base:
        url: http://localhost:8180
  price:
    service:
      base:
        url: http://localhost:8280

